- name: add the nodesource gpg key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: add node.js repositories
  apt_repository:
    repo: "{{ item }} https://deb.nodesource.com/node_12.x {{ ansible_distribution_release }} main"
    filename: nodesource
  with_items:
    - deb
    - deb-src

- name: install node.js
  apt:
    name: nodejs
    update_cache: yes
