- name: install subversion server packages
  apt:
    name: [
      subversion,
      apache2,
      libapache2-mod-svn,
      libsvn-dev,
      python-passlib,
    ]
    update_cache: yes

- name: enable subversion apache2 modules
  apache2_module:
    name: "{{ item }}"
  with_items:
    - dav
    - dav_svn
  notify: restart apache2

- name: create svn directory
  file:
    path: /var/lib/svn
    state: directory
    owner: www-data
    group: www-data
    mode: 0775

- name: create svn user
  htpasswd:
    path: /etc/apache2/dav_svn.passwd
    name: admin
    password: password
    owner: root
    group: www-data
    mode: 0640

- name: overwrite dav_svn.conf
  copy:
    src: files/dav_svn.conf
    dest: /etc/apache2/mods-available/dav_svn.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apache2
