- name: install subversion
  apt:
    name: subversion
    update_cache: yes
- name: install apache
  apt:
    name: apache2
    update_cache: yes
- name: install libapache2-mod-svn
  apt:
    name: libapache2-mod-svn
    update_cache: yes
- name: install libsvn-dev
  apt:
    name: libsvn-dev
    update_cache: yes
- name: enable dav apache2 module
  apache2_module:
    name: dav
  notify: restart apache2
- name: enable dav_svn apache2 module
  apache2_module:
    name: dav_svn
  notify: restart apache2
- name: create svn directory
  file:
    path: /var/lib/svn
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
- name: install python passlib
  apt:
    name: python-passlib
    update_cache: yes
- name: create svn user
  htpasswd:
    path: /etc/apache2/dav_svn.passwd
    name: admin
    password: password
    owner: root
    group: www-data
    mode: 0640
- name: overwrite dav_svn.conf
  copy:
    src: files/dav_svn.conf
    dest: /etc/apache2/mods-available/dav_svn.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apache2
